kstobiecki/WDP-2001-02

package-lock.json, src/components/layout/CompanyClaim/CompanyClaim.js, src/components/layout/CompanyClaim/CompanyClaim.module.scss
enable cartCounter to contain 5digit order
=> WDP200102-2

src/components/common/Button/Button.js, src/components/common/Button/Button.module.scss, src/components/common/ProductBox/ProductBox.js, src/redux/initialState.js
https://projects.kodilla.com/browse/WDP200102-5
=> WDP200102-5

src/components/common/ProductBox/ProductBox.js, src/components/common/ProductBox/ProductBox.module.scss, src/redux/initialState.js
it should be possible (if needed) to display on ProductBox old price.
=> Wdp200102 6

src/components/layout/Footer/Footer.js
Nie potrafię w żaden sposób ostylować, ani ukryć tego pustego divu, który znajduje się w sekcji copyright. Na razie go wykomentowałam.
=> Add RWD for footer columns, start working on copyright section

src/components/common/FeatureBox/FeatureBox.js, src/components/common/FeatureBox/FeatureBox.module.scss, src/components/features/FeatureBoxes/FeatureBoxes.js
Chodzi o elementy "Free shipping", etc.
Pierwszy element ma ustawiony na sztywno stan "hover". Każda z korzyści powinna być linkiem i mieć hover.
=> Wdp200102 3

src/components/common/FeatureBox/FeatureBox.js, src/components/common/FeatureBox/FeatureBox.module.scss, src/components/features/FeatureBoxes/FeatureBoxes.js, src/components/features/ProductSearch/ProductSearch.js, src/components/features/ProductSearch/ProductSearch.module.scss
Select nie jest prawidłowo ostylowany:
chyba zły rozmiar czcionki
zostaje outline po zmianie kategorii
brak hoverów
Do poprawy wedle designu.
=> Wdp200102 7

src/components/common/Button/Button.module.scss, src/components/features/NewFurniture/NewFurniture.module.scss, src/components/layout/CompanyClaim/CompanyClaim.module.scss, src/components/layout/Footer/Footer.module.scss, src/components/layout/MenuBar/MenuBar.module.scss, src/components/layout/TopBar/TopBar.module.scss, src/styles/settings.scss
https://projects.kodilla.com/browse/WDP200102-9
=> WDP200102-9

src/components/layout/CompanyClaim/CompanyClaim.js, src/components/layout/CompanyClaim/CompanyClaim.module.scss, src/components/layout/TopBar/TopBar.js, src/components/layout/TopBar/TopBar.module.scss
Trochę siermiężny sposób na dodanie tego RWD, ale działa ;)
=> Add RWD for topbar and banner

package-lock.json, package.json, src/components/common/Swipeable/Swipeable.js, src/components/features/NewFurniture/NewFurniture.js, src/components/views/Homepage/Homepage.js
https://projects.kodilla.com/browse/WDP200102-13
Dodatkowo dodam, że wykorzystałem komponent swipe, który nie ma animacji. 
Po dodaniu funkcjonalności z zadania WDP200102-19 galeria powinna ładnie się wygaszać podczas swipowania
=> WDP200102-13

src/components/features/ProductSearch/ProductSearch.js, src/components/features/ProductSearch/ProductSearch.module.scss
Obecnie to jest zrobione na elemencie <select>. Powinno być zrobione inaczej, aby była możliwość rozwijania po najechaniu myszką. 
Od technicznej strony chyba najlepiej będzie zrobić np. strukturę ul>li>ul>li, w którym ul niższego poziomu wyświetla się kiedy jego rodzic (li) ma :hover (do decyzji deva czy to będą ul>li, czy inne elementy)
Lepiej unikać JSa, żeby działanie menu nie było zależne od wczytania skryptów.
=> CHANGE the way of selecting category from <select> to option:hover

src/components/common/Button/Button.module.scss, src/components/features/NewFurniture/NewFurniture.module.scss, src/components/layout/Footer/Footer.module.scss, src/components/layout/TopBar/TopBar.module.scss, src/redux/initialState.js, src/styles/settings.scss
Poprawki animacji i dodanie dodatkowych produktów do initialState
=> WDP200102-19-fix

src/components/features/Feedback/Feedback.js, src/components/features/Feedback/Feedback.module.scss, src/components/features/Feedback/FeedbackContainer.js, src/components/features/NewFurniture/NewFurniture.js, src/components/views/Homepage/Homepage.js, src/redux/initialState.js, src/redux/opinionsRedux.js, src/redux/store.js
W tym tasku należy dodać na stronie sekcję "Feedback" według designu:
https://uploads.kodilla.com/bootcamp/wdp/group-project-01/section-feedback.png
Ten task dotyczy tylko wyglądu, bez funkcjonalności! W ramach tego zadania należy zrobić komponent (lub komponenty), ostylować go, a treści pobierać ze stanu aplikacji.
Tak jak w innych elementach tego typu, kropka przy aktywnym slajdzie i na hover ma być pomarańczowa.
=> Wdp200102 33

src/components/features/ProductSearch/ProductSearch.module.scss, src/components/layout/MenuBar/MenuBar.js, src/components/layout/MenuBar/MenuBar.module.scss
Nie mam pojęcia, dlaczego nie działa mi :hover na hamburgerze. Proszę o jakąś podpowiedź.
=> Wdp200102 14

package-lock.json, src/App.js, src/components/features/NewFurniture/NewFurniture.js, src/components/features/NewFurniture/NewFurnitureContainer.js, src/components/layout/MainLayout/MainLayout.js, src/components/layout/MainLayout/MainLayoutContainer.js, src/redux/initialState.js, src/redux/store.js, src/redux/viewportRedux.js
https://projects.kodilla.com/browse/WDP200102-20
=> WDP200102-20

src/components/features/Promotion/Promotion.js, src/components/features/Promotion/Promotion.module.scss, src/components/features/Promotion/Promotion.test.js, src/components/views/Homepage/Homepage.js, src/redux/initialState.js
Zadanie dotyczyło stylowania, więc obrazki i teksty nie pobierają się ze stanu aplikacji. Są wrzucone na sztywno. Tak czy inaczej dodałam dane, które mają pojawić się w boxach do initalData.js. Zrobiłam też destrukturyzację.
=> Wdp200102 25

src/components/features/Feedback/Feedback.js, src/components/features/Feedback/Feedback.module.scss, src/components/features/NewFurniture/NewFurniture.js, src/components/features/NewFurniture/NewFurniture.module.scss
W tym zadaniu należy dodać animację slidera w sekcji "Feedback":
https://uploads.kodilla.com/bootcamp/wdp/group-project-01/section-feedback.png
Ma działać przesuwanie slajdów za pomocą komponentu Swipeable (jest na niego osobne zadanie – jeśli nie jest gotowe to trzeba przygotować funkcje, które będą wykonywane przy swipe w lewo i w prawo).
=> Wdp200102 34

package-lock.json, src/components/features/Gallery/Gallery.js, src/components/features/Gallery/Gallery.module.scss, src/components/features/Gallery/GalleryContainer.js, src/components/features/GalleryCarousel/GalleryCarousel.js, src/components/features/GalleryCarousel/GalleryCarousel.module.scss, src/components/features/NewFurniture/NewFurniture.js, src/components/views/Homepage/Homepage.js, src/redux/galeriesRedux.js, src/redux/initialState.js, src/redux/productsRedux.js, src/styles/settings.scss
1. Taby ze sliderem po lewej:
Buttony po lewej stronie zdjęcia i element z gwiazdkami w prawym dolnym rogu mają działać analogicznie do podobnych elementów na stronie.
Na hover każdego buttona z lewej pojawia się przy nim tooltip.
W sliderze z thumbnailami pod głównym zdjęciem nieaktywne elementy mają nałożony półprzezroczysty overlay.
2. Duże zdjęcie po prawej to statyczny element, niezwiązany ze sliderem po lewej.
=> Wdp200102 27a

src/components/features/NewFurniture/NewFurniture.js, src/components/features/NewFurniture/NewFurniture.module.scss
Poprawa zepsutych dots w NewFurniture i poprawa stylów mobile dla dots
=> WDP-2001-02-20-fix

src/App.js, src/components/common/ProductBox/ProductBox.module.scss, src/components/features/FeatureBoxes/FeatureBoxes.js, src/components/features/FeatureBoxes/FeatureBoxes.module.scss, src/components/layout/CompanyClaim/CompanyClaim.js, src/components/layout/CompanyClaim/CompanyClaim.module.scss, src/components/layout/Header/Header.js, src/components/layout/MenuBar/MenuBar.js, src/components/layout/MenuBar/MenuBar.module.scss, src/components/layout/MenuBar/MenuBarContainer.js, src/redux/initialState.js, src/redux/navCategoriesRedux.js
1. RWD komponentu CompanyClaim (tam gdzie jest logo)
2. Zmiana wielkości zdjęć w komponencie ProductBox
3. Zmiana wielkości komponentów FeatureBoxes (tak, żeby na laptopie były 4 w jednym rzędzie)
4. Dodanie ReactRoutera w nawigacji
(mogłam sobie zapisywać, bo nie pamiętam, czy coś jeszcze zrobiłam)
=> Wdp200102 extra1

src/App.js, src/components/layout/MenuBar/MenuBar.js, src/components/views/ProductList/ProductList.js, src/components/views/ProductList/ProductList.module.scss, src/components/views/ProductList/ProductListContainer.js, src/redux/initialState.js, src/redux/productsRedux.js
1) create ProductList + style it
2) style basic heading for component (sorting)
=> Wdp200102 extra2
